import { ZohoField, MappingOptions, mapFieldType } from './mapper.js';

// e.g. "Module_Name_One" → "ZohoModuleNameOne"
function toInterfaceName(apiName: string): string {
  const pascal = apiName
    .split('_')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join('');
  return `Zoho${pascal}`;
}

function toJsDoc(label: string | undefined): string {
  if (!label || label.trim() === '') return '';
  const escaped = label.replace(/\*\//g, '*\\/');
  return `  /** ${escaped} */\n`;
}

function resolveFieldType(field: ZohoField, opts: MappingOptions = {}): string {
  if (field.data_type === 'subform') {
    if (!field.subform_fields || field.subform_fields.length === 0) return 'unknown[]';
    const subFields = field.subform_fields.filter((f) => f.api_name !== 'id');
    const props = subFields.map((f) => {
      const tsType = mapFieldType(f, opts);
      const optional = f.system_mandatory ? '' : '?';
      return `    ${f.api_name}${optional}: ${tsType};`;
    });
    return `Array<{\n    id: string;\n${props.join('\n')}\n  }>`;
  }
  return mapFieldType(field, opts);
}

export function generateInterface(
  moduleApiName: string,
  fields: ZohoField[],
  opts: MappingOptions = {}
): string {
  const interfaceName = toInterfaceName(moduleApiName);

  // id is hardcoded as string — Zoho metadata says bigint but the API returns strings
  const standardFields = fields.filter((f) => !f.custom_field && f.api_name !== 'id');
  const customFields = fields.filter((f) => f.custom_field && f.api_name !== 'id');

  const lines: string[] = [];

  lines.push(`// auto-generated by zoho-typegen — do not edit manually`);
  lines.push(`// Module: ${moduleApiName}\n`);
  lines.push(`export interface ${interfaceName} {`);
  lines.push(`  id: string;`);

  for (const field of standardFields) {
    const tsType = resolveFieldType(field, opts);
    const optional = field.system_mandatory ? '' : '?';
    const jsDoc = toJsDoc(field.field_label);
    if (jsDoc) lines.push(jsDoc.trimEnd());
    lines.push(`  ${field.api_name}${optional}: ${tsType};`);
  }

  if (customFields.length > 0) {
    lines.push('');
    lines.push(`  // Custom fields`);
    for (const field of customFields) {
      const tsType = resolveFieldType(field, opts);
      const optional = field.system_mandatory ? '' : '?';
      const jsDoc = toJsDoc(field.field_label);
      if (jsDoc) lines.push(jsDoc.trimEnd());
      lines.push(`  ${field.api_name}${optional}: ${tsType};`);
    }
  }

  lines.push(`}`);
  lines.push('');

  return lines.join('\n');
}

export function generateBarrel(modules: { apiName: string; fileName: string }[]): string {
  const lines: string[] = [];
  lines.push(`// auto-generated by zoho-typegen — do not edit manually`);
  lines.push('');

  for (const { apiName, fileName } of modules) {
    const interfaceName = toInterfaceName(apiName);
    const importPath = `./${fileName.replace(/\.ts$/, '')}`;
    lines.push(`export type { ${interfaceName} } from '${importPath}';`);
  }

  lines.push('');
  return lines.join('\n');
}
